ymş updated

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,14 +15,18 @@ jobs:
 
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2 # Güncelleme v1'den v2'ye
-      
+
     - name: Build Docker image
       run: docker build -t my-first-devops-project .
 
     - name: Test Docker image
       run: |
-        docker run -d -p 8080:80 my-first-devops-project
-        curl -f http://localhost:8080 || exit 1
+        result=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)
+        echo "test-result=$result" >> $GITHUB_ENV
 
-    - name: Cleanup Docker containers
-      run: docker ps -q | xargs docker stop
+    - name: Check Test Result
+      run: |
+        if [ "${{ env.test-result }}" != "200" ]; then
+          echo "Test failed"
+          exit 1 
+        fi
